Faceweb/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
]

Faceweb/mysite/pages/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
app_name = 'pages'
urlpatterns = [

    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('singup/', views.singup, name='singup'),
    path('studentaffair/', views.studentaffair, name='studentaffair'),
    url(r'^(?P<username>[0-9]+)/$', views.detail, name='detail'),
    path('stdcreate/', views.student_create, name='stdcreate'),
    path('tchcreate/', views.teacher_create, name='tchcreate'),

]

Faceweb/mysite/pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save

from django.dispatch import receiver



# Create your models here.






class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    classroom = models.CharField(max_length=7, blank=True)
    age = models.CharField(max_length=3, blank=True)
    birth_date = models.DateField(null=True, blank=True)


    def __str__(self):
        return self.user.username


   # def get_absolute_url(self):
    #    return reverse('post:detail', kwargs={'username': self.username})

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    classroom = models.CharField(max_length=3, blank=True)
    age = models.CharField(max_length=3, blank=True)

    def __str__(self):
        return self.user.username


class StudentAffairs(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)



    def __str__(self):
        return self.user.username



class Attendance(models.Model):
    student_id = models.CharField(max_length=20, null=True, blank=True)
    teacher_id = models.CharField(max_length=20, null=True, blank=True)
    lessons = models.CharField(max_length=15, null=True, blank=True)
    classroom = models.CharField(max_length=7, null=True, blank=True)
    attendance_date = models.DateField(null=True, blank=True)
    timing = models.CharField(max_length=20, null=True, blank=True)
    status = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
         return self.classroom


class TimeTable(models.Model):
    classroom = models.CharField(max_length=7)
    dayname = models.CharField(max_length=20)
    lesson = models.CharField(max_length=20)
    l_time = models.CharField(max_length=202)



    def __str__(self):
        return '%s %s %s %s' % (self.classroom, self.dayname, self.time, self.lesson,)




class TeacherLesson(models.Model):
    classroom = models.CharField(max_length=7)
    lesson = models.CharField(max_length=20)
    teacher_id = models.CharField(max_length=20)

    def __str__(self):
        return '%s %s' % (self.teacher_id, self.lesson)

Faceweb/mysite/pages/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Student
from .models import Teacher


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='User Name')
    password = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('user name or password entered incorrectly')
        return super(LoginForm, self).clean()





class SingUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',)


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = [

            'classroom',
            'age',
            'birth_date',


        ]

class TeacherForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = [

            'classroom',
            'age',
        ]

Faceweb/mysite/pages/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from .forms import SingUpForm
from .forms import StudentForm
from .forms import TeacherForm
from .models import Student
from .models import User
from .models import Teacher
from .models import Attendance

from django.contrib.auth.models import Group
# Create your views here.


def detail(request, username):
    attendance_list = Attendance.objects.all()
    attendance_list1 = Attendance.objects.all()
    start_date = request.GET.get('sd')
    finish_date =request.GET.get('fd')

    start_date1 = request.GET.get('sd1')
    finish_date1 = request.GET.get('fd1')
    select_lesson = request.GET.get('sl')
    select_classroom = request.GET.get('cl')
    if start_date1 and finish_date1 and select_classroom:
        attendance_list1 = attendance_list1.filter(attendance_date__range=[start_date1, finish_date1], teacher_id=username, classroom=select_classroom)
    if start_date and finish_date or select_lesson:
        attendance_list = attendance_list.filter(attendance_date__range=[start_date, finish_date], lessons=select_lesson, student_id=username)
    try:
        users = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404("Student doesnt not exist")
    return render(request, 'detail.html', {'users': users, 'attendance_list': attendance_list, 'attendance_list1': attendance_list1 })



def studentaffair(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    return render(request, 'studentaffair/controller.html', {'students': students, 'teachers': teachers} )


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        #result = user.groups.filter(name='Students').exists()
        #if result:
        return redirect('pages:studentaffair')
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('pages:login')


def singup(request):
    form = SingUpForm(request.POST or None)
    slc = request.POST.get('select')
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        #group = Group.objects.get(name=group1)
        #user.groups.add(group)
        login(request, user)

        if slc == "Student":
            return redirect('pages:stdcreate')
        else:
            return redirect('pages:tchcreate')
    else:
        form = SingUpForm()
        print("jdj")

    return render(request, 'singup.html', {'form': form})


def student_create(request):
    form = StudentForm(request.POST or None)
    if form.is_valid():
        student = form.save(commit=False)
        student.user = request.user
        student.save()
        return redirect('pages:studentaffair')
    context = {
        'form': form,

    }
    return render(request, 'student_create.html', context)


def teacher_create(request):
    form = TeacherForm(request.POST or None)
    if form.is_valid():
        teacher = form.save(commit=False)
        teacher.user = request.user
        teacher.save()
        return redirect('pages:studentaffair')
    context = {
         'form': form,
     }
    return render(request, 'teacher_create.html', context)

Faceweb/mysite/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.css' %}">
</head>
<body>
     <nav class="navbar navbar-expand-lg nav-bg">
		<a class="navbar-brand" href="https://en.ankara.edu.tr/"><img src="{% static 'media/logo-mini.png' %}" style="width: 100px;"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		     	<li class="nav-item active">
		        	<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
		      	</li>
		      	<li class="nav-item">
		        	<a class="nav-link" href="https://webmail.ankara.edu.tr/">E-mail</a>
		      	</li>
		      	<li class="nav-item">
		        	<a class="nav-link" href="https://en.ankara.edu.tr/contact/">Contact</a>
		      	</li>
				{% if request.user.is_authenticated %}
				<li class="nav-item">
		        	<a class="nav-link" href="{% url 'pages:logout' %}">Logout</a>
		      	</li>
				{% endif %}
		    </ul>
		</div>
	</nav>


    {% block body%}
    {% endblock%}







	<script src="{% static 'js/jquery-3.4.1.min.js' %}" type="text/javascript" ></script>
	<script src="{% static 'js/popper.min.js' %}" type="text/javascript" ></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript" ></script>
	<script src="{% static 'js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.dataTables.js' %}" type="text/javascript"></script>





<script type="text/javascript">
		$('.datepicker').datepicker({
    startDate: '-3d',
    clearBtn: true,
    todayHighlight: true,
    autoclose: true,
    format: 'yyyy/mm/dd'
});


	</script>

	<script type="text/javascript">

   $(document).ready(function() {
    $('#example').DataTable({
    	 searching: false,
   		 ordering:  true,
   		 scrollY: 400,
   		 paging: false
    }

    );
} );
	</script>

</body>
</html>

Faceweb/mysite/templates/detail.html
{% extends 'base.html'%}

{%load static%}


{% block body %}
{% if users.student %}
    <div class="container information">
		<h3><i class="fas fa-user"></i> User Information</h3>
		<div class="card mb-3" >
		  	<div class="row no-gutters">
		    	<div class="col-md-4">

		    	</div>
		    	<div class="col-md-8">
		      		<div class="card-body">
						<ul class="nav flex-column">
						  	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Name-Surname:</h5>
		        					<span class="inf">{{users.first_name}} {{users.last_name}}</span>
		        				</div>
						 	</li>
						  	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Student Id:</h5>
		        					<span class="inf">{{users.username}}</span>
		        				</div>
						 	</li>
						 	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Age:</h5>
		        					<span class="inf">{{users.student.age}}</span>
		        				</div>
						  	</li>
						  	<li class="nav-item">
						   		<div class="section col-md-6">
		        					<h5 class="title">Birth Date:</h5>
		        					<span class="inf">{{users.student.birth_date}}</span>
		        				</div>
						  	</li>
						  	<li class="nav-item">
						   		<div class="section col-md-6">
		        					<h5 class="title">Class:</h5>
		        					<span class="inf">{{users.student.classroom}}</span>
		        				</div>
						  	</li>

						</ul>
		    	</div>
		    </div>

		</div>

	</div>
    </div>


    <div class="attendence ">
		<h3 class="title">ATTENDENCE SEARCH</h3>
		<div class="search  container-fluid">
			<h4>VIEW DETAILED ATTENDENCE</h4>
            <form method="GET">
                <label>Start Date</label>
               <!-- <input name="sd" value="{{request.GET.sd}}" class="datepicker" data-date-format="yyyy/mm/dd" placeholder="YYYY-MM-DD"> -->
                <input name="sd" value="{{request.GET.sd}}" type="date" placeholder="YYYY-MM-DD">
                <label>End Date</label>
                <input name="fd" value="{{request.GET.fd}}" type="date" placeholder="YYYY-MM-DD">

                <label>Lessons</label>
                <select name="sl" value="{{request.GET.sl}}"  class="custom-select col-lg-2 col-xl-2">
					<option>Math</option>
                    <option>Physics</option>
                    <option>Biology</option>
                    <option>Chemistry</option>
                </select>
                <button class="btn btn-lg btn-primary" type="submit"><i class="fas fa-search"></i>Search


            </form>


		</div>

		<h3>DETAILS</h3>
		<table id="example" class="table display bg-primary">
			<thead>
				<tr>
					<th scope="col">Lessons</th>
					<th scope="col">Date</th>
					<th scope="col">Timing</th>
					<th scope="col">Status</th>
					<th scope="col">Teacher Name</th>
				</tr>
			</thead>
			<tbody>
            {% for attendance in attendance_list %}
				<tr>
					<td>{{attendance.lessons}}</td>
					<td>{{attendance.attendance_date}}</td>
					<td>{{attendance.timing}}</td>
					<td>{{attendance.status}}</td>
					<td>{{attendance.teacher_id}}</td>
				</tr>
            {% endfor %}
			</tbody>
		</table>

	</div>
{% endif %}

{% if users.teacher %}
	<div class="container information">
		<h3><i class="fas fa-user"></i> User Information</h3>
		<div class="card mb-3" >
		  	<div class="row no-gutters">
		    	<div class="col-md-4">

		    	</div>
		    	<div class="col-md-8">
		      		<div class="card-body">
						<ul class="nav flex-column">
						  	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Name-Surname:</h5>
		        					<span class="inf">{{users.first_name}} {{users.last_name}}</span>
		        				</div>
						 	</li>
						  	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Teacher Id:</h5>
		        					<span class="inf">{{users.username}}</span>
		        				</div>
						 	</li>
						 	<li class="nav-item">
						    	<div class="section col-md-6">
		        					<h5 class="title">Age:</h5>
		        					<span class="inf">{{users.teacher.age}}</span>
		        				</div>
						  	</li>

						  	<li class="nav-item">
						   		<div class="section col-md-6">
		        					<h5 class="title">Class:</h5>
		        					<span class="inf">{{users.teacher.classroom}}</span>
		        				</div>
						  	</li>

						</ul>
		    	</div>
		    </div>

		</div>

	</div>
    </div>
	 <div class="attendence ">
		<h3 class="title">ATTENDENCE SEARCH</h3>
		<div class="search  container-fluid">
			<h4>VIEW DETAILED ATTENDENCE</h4>
            <form method="GET">
                <label>Start Date</label>
               <!-- <input name="sd" value="{{request.GET.sd}}" class="datepicker" data-date-format="yyyy/mm/dd" placeholder="YYYY-MM-DD"> -->
                <input name="sd1" value="{{request.GET.sd}}" type="date" placeholder="YYYY-MM-DD">
                <label>End Date</label>
                <input name="fd1" value="{{request.GET.fd}}" type="date" placeholder="YYYY-MM-DD">
				<label>Classroom</label>
				<select name="cl" value="{{request.GET.sl}}"  class="custom-select col-lg-2 col-xl-2">
					<option>3-A</option>
                    <option>3-B</option>
                </select>

                <button class="btn btn-lg btn-primary" type="submit"><i class="fas fa-search"></i>Search


            </form>


		</div>

		<h3>DETAILS</h3>
		<table id="example" class="table display bg-primary">
			<thead>
				<tr>
					<th scope="col">Lessons</th>
					<th scope="col">Date</th>
					<th scope="col">Timing</th>
					<th scope="col">Status</th>
					<th scope="col">Student Id</th>
				</tr>
			</thead>
			<tbody>
            {% for attendance in attendance_list1 %}
				<tr>
					<td>{{attendance.lessons}}</td>
					<td>{{attendance.attendance_date}}</td>
					<td>{{attendance.timing}}</td>
					<td>{{attendance.status}}</td>
					<td>{{attendance.student_id}}</td>
				</tr>
            {% endfor %}
			</tbody>
		</table>

	</div>
{% endif %}
    {{username}}
    <h2>fdf</h2>
    {{users.first_name}}
    {{users.last_name}}
    {{users.student.age}}

{% endblock %}

Faceweb/mysite/templates/index.html
{%extends 'base.html'%}

{% block body %}
<p>index</p>
<a href="" class="btn btn-success">Add Student</a>
<a href="" class="btn btn-primary">Add Teacher</a>{{user.username}}
{% endblock %}

Faceweb/mysite/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container col-lg-3 log ">
        <h2 class="header">Login</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}

{{user.username}}
             <button class="btn btn-success" type="submit">Login</button>
         </form>

    </div>

{% endblock %}

Faceweb/mysite/templates/singup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {%block body%}

    <div class="container col-lg-5 col-xl-5 col-md-5">
        <h2>Sign up</h2>
        <form method="POST">
            {% csrf_token %}
            <select name="select">
                <option>Student</option>
                <option>Teacher</option>
            </select>
            {{ form|crispy }}
            <button  class="btn btn-success" type="submit">Step 2</button>
        </form>
    </div>


    {% endblock %}

Faceweb/mysite/templates/student_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
  <div class="container">
       <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Create</button>
        </form>
  </div>

{% endblock %}

Faceweb/mysite/templates/studentaffair/controller.html
{% extends 'base.html' %}
{% block body %}
  <br>
<br>
<div class="container">
	<h1 class="ctrl-title">CONTROL OF SYSTEM</h1>
	<br>
	<br>
    <br>
    <div class="col-lg-6 offset-lg-5" >
        <a class="btn btn-success" href="{% url 'pages:singup'%}"><i class="fas fa-plus"></i>Add User</a>
    </div>

</div>

<br>
<br>

<div class="container-fluid control-table ">

        <div class="container ">
            <h2 class="text-center header">STUDENT LIST</h2>

            <table class="table table-sm table-dark">
                <thead>
                    <tr>
                        <th scope="col" >Student id</th>
                        <th scope="col">First name</th>
                        <th scope="col">Last name</th>
                        <th scope="col">Class</th>

                    </tr>
                </thead>
                <tbody>
                {% for student in students %}
                    <tr>
                        <td><a href="/pages/{{student.user}}/">{{student.user}}</a></td>
                        <td>{{student.user.first_name}}</td>
                        <td>{{student.user.last_name}}</td>
                        <td>{{student.classroom}}</td>

                    </tr>
                 {% endfor %}
                </tbody>
            </table>

       </div>
        <div class="container">
            <h2 class="text-center">TEACHER LIST</h2>
             <table class="table table-sm table-dark">
                <thead>
                    <tr>
                        <th scope="col" >Student id</th>
                        <th scope="col">First name</th>
                        <th scope="col">Last name</th>

                    </tr>
                </thead>
                <tbody>
                {% for teacher in teachers %}
                    <tr>
                        <td><a href="/pages/{{teacher.user}}/">{{teacher.user}}</a></td>
                        <td>{{teacher.user.first_name}}</td>
                        <td>{{teacher.user.last_name}}</td>

                    </tr>
                 {% endfor %}
                </tbody>
            </table>

        </div>


</div>


{% endblock %}

Faceweb/mysite/templates/teacher_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
         <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Create</button>
        </form>
    </div>
{% endblock %}